import pulumi
from pulumi_aws import s3
from network import base_network

#CONFIGURAÇÃO DE NETWORK, ULTILIZA O CONSTRUTOR CRIADO EM NETWORK NO ARQUIVO base_network.
#APENAS CONFIGURAR AS VARIÁVEIS ABAIXO.

NAME = "ayo" #VPC NAME
BLOCK_IP_VPN = "10.1.0.0/16" # BLOCK VPC
BLOCK_IP_SUBNET_PUBLIC = "10.1.1.0/24" # BLOCK SUBNET PUBLIC
BLOCK_IP_SUBNET_PRIVATE = "10.1.2.0/24" # BLOCK SUBNET PRIVATE

base_network.network_constructor(NAME, BLOCK_IP_VPN, BLOCK_IP_SUBNET_PUBLIC, BLOCK_IP_SUBNET_PRIVATE)