import pulumi
from pulumi_aws import s3
from network import network_constructor


# CONFIGURAÇÃO DE NETWORK, ULTILIZA O CONSTRUTOR CRIADO EM NETWORK NO ARQUIVO base_network.
# APENAS CONFIGURAR AS VARIÁVEIS ABAIXO.

NAME = "VPC_NAME"
BLOCK_IP_VPN = "BLOCK_IP_VPN"
BLOCK_IP_SUBNET_PUBLIC = "BLOCK_IP_SUBNET_PUBLIC"
BLOCK_IP_SUBNET_PRIVATE = "BLOCK_IP_SUBNET_PRIVATE"

network_constructor(NAME, BLOCK_IP_VPN, BLOCK_IP_SUBNET_PUBLIC, BLOCK_IP_SUBNET_PRIVATE)